### PR TITLE
fix(countryController/getSinglePosition): fixes get single position controller

### LINKED ISSUE #12: Issue with Uppercase countries
This is small but I think it would make the experience better. In the docs where we get country position by name, where we send a POST Request to /api/v1.0/countries/positions with the `country` parameter in the body, I noticed that you capitalized it but in reality it doesn't return any data. I also tried with non-existent country names and it kept returning the same strings. For a moment there I thought the API was broken. So I took a look at https://github.com/MartinsOnuoha/countriesAndCitiesAPI/blob/1742ee9dd6c34bb306aac8a1c9f0304e6d190d60/controllers/countryController.js#L90 and found out that you weren't formatting the input to lowercase just the data from the model. Also I think it should fail when a non-existent country is sent. I could make a PR with the suggested changes if you want.

### PR DESCRIPTION
**Pull request by iambenkay**
- fixes case sensitive search for countries
- adds an error handler for countries that are not found

Here's the PR man.

Closes #12

### CODE REVIEW

File: controllers/countryController.js [hunk 1]
```diff
@@ -84,11 +84,20 @@ class CountryController {
...
         }
+        const data = positions.find(x => x.name.toLowerCase() === country.toLowerCase())
+        
+        // Just incase there is no country with the provided name
+        if (!data) {
+            return res.status(404).json({
+                error: true,
+                msg: 'Country not found'
+            })
+        }
```
Comment (MartinsOnuoha) [inline controllers/countryController.js:95]: Here you can use the Respond helper class that exists, instead of returning the `res` object.

So it looks something like:
```javascript
return Respond.error(res, 'country not found', 404);
```

**Comment by iambenkay** [comment]
I have made the changes in the latest commit.
